apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sigla-thorntail
  labels:
    cloud.googleapis.com/location: europe-west4
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/cloudsql-instances: $project_id:europe-west4:pdb-team-digi-sigla-001
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/vpc-access-connector: projects/$project_id/locations/europe-west4/connectors/vac-team-digi-sigla
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 1
      timeoutSeconds: 3600
      containers:
      - image: europe-west4-docker.pkg.dev/$project_id/ar-team-digi-sigla-poc-001/sigla-main:release
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: LC_LL
          value: it_IT.UTF-8
        - name: LC_ALL
          value: it_IT.UTF-8
        - name: LANG
          value: it_IT.UTF-8
        - name: LANGUAGE
          value: it_IT:it
        - name: THORNTAIL_DATASOURCES_DATA-SOURCES_SIGLA_CONNECTION-URL
          value: jdbc:postgresql://$db_private_ip:5432/sigladb?schema=public
        - name: THORNTAIL_PROJECT_STAGE
          value: demo-postgres
        - name: THORNTAIL_DATASOURCES_DATA-SOURCES_SIGLA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: latest
        - name: THORNTAIL_UNDERTOW_SERVLET-CONTAINERS_DEFAULT_SESSION-COOKIE-SETTING_COMMENT
          value: ;
        - name: CORS_ALLOW-ORIGIN
          value: $sigla_ng_url
        resources:
          limits:
            cpu: 4000m
            memory: 8192Mi
